name: Trigger auto deployment for shadowpm-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/shadowpm-api-AutoDeployTrigger-6c279aac-8fdf-4228-b54e-0d06bf81fec5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SHADOWPMAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SHADOWPMAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SHADOWPMAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: saturnhack698ca5.azurecr.io
          registryUsername: ${{ secrets.SHADOWPMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHADOWPMAPI_REGISTRY_PASSWORD }}
          containerAppName: shadowpm-api
          resourceGroup: saturn-hack
          imageToBuild: saturnhack698ca5.azurecr.io/shadowpm-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


